# Generated by Django 6.0 on 2026-01-07 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('corrective', 'Corretiva'), ('preventive', 'Preventiva'), ('installation', 'Instalação'), ('consulting', 'Consultoria')], max_length=50, verbose_name='Tipo de Ordem')),
                ('equipment', models.CharField(max_length=200, verbose_name='Equipamento')),
                ('problem_type', models.CharField(max_length=200, verbose_name='Tipo de Problema')),
                ('description', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('status', models.CharField(choices=[('open', 'Em Aberto'), ('in_progress', 'Em Andamento'), ('pending', 'Aguardando Aprovação'), ('finished', 'Finalizado'), ('canceled', 'Cancelado')], default='open', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.client', verbose_name='Cliente')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
    ]
