# Generated by Django 6.0 on 2026-01-08 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Equipamento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de Ordem')),
            ],
            options={
                'verbose_name': 'Tipo de Ordem',
                'verbose_name_plural': 'Tipos de Ordem',
            },
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de Problema')),
            ],
            options={
                'verbose_name': 'Tipo de Problema',
                'verbose_name_plural': 'Tipos de Problema',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.equipment', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.ordertype', verbose_name='Tipo de Ordem'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.problemtype', verbose_name='Tipo de Problema'),
        ),
    ]
