# Generated by Django 6.0.1 on 2026-01-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_equipment_ordertype_problemtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Posto de Alocação'),
        ),
    ]
