# Generated by Django 6.0.1 on 2026-01-09 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_userprofile_job_title_userprofile_station'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de Equipamento')),
            ],
            options={
                'verbose_name': 'Tipo de Equipamento',
                'verbose_name_plural': 'Tipos de Equipamento',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='area_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo de Áreas'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='area_subgroup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subgrupo de Áreas'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='call_type',
            field=models.CharField(blank=True, choices=[('acidente_com_afastamento', 'Acidente com Afastamento'), ('acidente_sem_afastamento', 'Acidente sem Afastamento'), ('acompanhamento', 'Acompanhamento'), ('anomalia_critica', 'Anomalia Crítica'), ('anomalia_simples', 'Anomalia Simples'), ('chamado', 'Chamado'), ('melhoria', 'Melhoria'), ('preventiva', 'Preventiva'), ('processo', 'Processo'), ('quebra', 'Quebra'), ('situacao_risco', 'Situação de Risco')], max_length=50, null=True, verbose_name='Tipo de Chamado'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Limite para Execução'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/', verbose_name='Imagem do Evento'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='system',
            field=models.CharField(blank=True, choices=[('BMS', 'BMS'), ('CFTV', 'CFTV'), ('COMBATE_INCENDIO', 'COMBATE INCENDIO'), ('CONTROLE_FUMACA', 'CONTROLE FUMAÇA'), ('SCA', 'SCA'), ('SDAI', 'SDAI')], max_length=50, null=True, verbose_name='Sistema'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.ordertype', verbose_name='Tipo de Ordem'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.equipmenttype', verbose_name='Tipo de Equipamento'),
        ),
        migrations.CreateModel(
            name='TicketUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição da Evolução')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ticket_updates/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Evolução do Chamado',
                'verbose_name_plural': 'Evoluções do Chamado',
                'ordering': ['created_at'],
            },
        ),
    ]
