# Generated by Django 6.0.1 on 2026-01-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_equipmenttype_ticket_area_ticket_area_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact1_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contato 1 (Email)'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact1_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato 1 (Nome)'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact1_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato 1 (Telefone)'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact2_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contato 2 (Email)'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact2_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato 2 (Nome)'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact2_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato 2 (Telefone)'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2'),
        ),
    ]
