# Generated by Django 6.0.1 on 2026-01-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_client_contact1_email_client_contact1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Empresa'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Próprio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Administrador'), ('technician', 'Técnico'), ('operator', 'Operador'), ('standard', 'Padrão')], default='standard', max_length=20),
        ),
    ]
