# Generated by Django 6.0.1 on 2026-01-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_estimated_time_ticketfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('color', models.CharField(default='#6c757d', help_text='Ex: #FF0000 para vermelho', max_length=20, verbose_name='Cor (Hex)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviço',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='tickets.category', verbose_name='Categorias de Serviço'),
        ),
    ]
