# Generated by Django 6.0.1 on 2026-01-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_category_ticket_start_date_ticket_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Sistema')),
                ('color', models.CharField(default='#6c757d', help_text='Ex: #FF0000 para vermelho', max_length=20, verbose_name='Cor (Hex)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='system',
        ),
        migrations.AddField(
            model_name='ticket',
            name='systems',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='tickets.system', verbose_name='Sistemas'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
