# Generated by Django 6.0.1 on 2026-01-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_system_remove_ticket_categories_remove_ticket_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30, help_text='Tempo de inatividade para desconectar o usuário automaticamente.', verbose_name='Tempo de Sessão (minutos)')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
