# Generated by Django 6.0.1 on 2026-01-11 18:55

from django.conf import settings
from django.db import migrations, models


def migrate_technicians(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    for ticket in Ticket.objects.all():
        if ticket.technician:
            ticket.technicians.add(ticket.technician)

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Técnicos Responsáveis'),
        ),
        migrations.RunPython(migrate_technicians),
        migrations.RemoveField(
            model_name='ticket',
            name='technician',
        ),
    ]
