# Generated by Django 6.0.1 on 2026-01-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_remove_ticket_technician_ticket_technicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos/', verbose_name='Logomarca'),
        ),
    ]
