# Generated by Django 6.0.1 on 2026-01-12 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_client_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketUpdateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ticket_updates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tickets.ticketupdate')),
            ],
            options={
                'verbose_name': 'Imagem da Evolução',
                'verbose_name_plural': 'Imagens da Evolução',
            },
        ),
    ]
