# Generated by Django 6.0.1 on 2026-01-13 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticketupdateimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento/Área'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='tickets.userprofile', verbose_name='Supervisor/Gerente'),
        ),
    ]
