# Generated by Django 6.0.1 on 2026-01-13 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_notification_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='final_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Final (Resolução)'),
        ),
        migrations.CreateModel(
            name='ClientHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Hub/Loja')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubs', to='tickets.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Hub/Loja',
                'verbose_name_plural': 'Hubs/Lojas',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.clienthub', verbose_name='Hub/Loja'),
        ),
    ]
