# Generated by Django 6.0.1 on 2026-01-13 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_ticket_final_description_clienthub_ticket_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='tickets.equipment', verbose_name='Equipamentos'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.equipment', verbose_name='Equipamento (Legacy)'),
        ),
    ]
