# Generated by Django 6.0.1 on 2026-01-13 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_ticket_equipments_alter_ticket_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de OS')),
            ],
            options={
                'verbose_name': 'Tipo de OS',
                'verbose_name_plural': 'Tipos de OS',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='call_type',
            field=models.CharField(blank=True, choices=[('acidente_com_afastamento', 'Acidente com Afastamento'), ('acidente_sem_afastamento', 'Acidente sem Afastamento'), ('acompanhamento', 'Acompanhamento'), ('anomalia_critica', 'Anomalia Crítica'), ('anomalia_simples', 'Anomalia Simples'), ('chamado', 'Chamado'), ('melhoria', 'Melhoria'), ('preventiva', 'Preventiva'), ('processo', 'Processo'), ('quebra', 'Quebra'), ('situacao_risco', 'Situação de Risco')], max_length=50, null=True, verbose_name='Tipo de Chamado (Legacy)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.tickettype', verbose_name='Tipo de Chamado'),
        ),
    ]
