# Generated by Django 6.0.1 on 2026-01-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_tickettype_alter_ticket_call_type_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'verbose_name': 'Tipo de Chamado', 'verbose_name_plural': 'Tipos de Chamados'},
        ),
        migrations.AddField(
            model_name='clienthub',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (Responsável)'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tipo de Chamado'),
        ),
    ]
