# Generated by Django 6.0.1 on 2026-01-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_ticket_leankeep_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthub',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hub_logos/', verbose_name='Logomarca do Hub'),
        ),
    ]
