# Generated by Django 6.0.1 on 2026-01-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_clienthub_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='technician_type',
            field=models.CharField(choices=[('fixo', 'Fixo'), ('volante', 'Volante')], default='fixo', max_length=10, verbose_name='Tipo de Técnico'),
        ),
    ]
