# Generated by Django 6.0.1 on 2026-01-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_userprofile_technician_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fixed_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_technicians', to='tickets.client', verbose_name='Empresa (Fixo)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fixed_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_technicians', to='tickets.clienthub', verbose_name='Hub/Loja (Fixo)'),
        ),
    ]
