# Generated by Django 6.0.1 on 2026-01-23 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_userprofile_fixed_client_userprofile_fixed_hub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(verbose_name='Agendado para')),
                ('multi_client', models.BooleanField(default=False, verbose_name='Atenderá mais clientes na viagem?')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('planned', 'Planejado'), ('pending_contract', 'Pendente de Contrato')], default='planned', max_length=20, verbose_name='Status da Viagem')),
                ('ticket_status', models.CharField(choices=[('concluded', 'Concluída'), ('issued', 'Emitida'), ('pending', 'Pendente'), ('na', 'Não se Aplica')], default='pending', max_length=20, verbose_name='Status Passagem (Ticket)')),
                ('hotel_status', models.CharField(choices=[('concluded', 'Concluída'), ('issued', 'Emitida'), ('pending', 'Pendente'), ('na', 'Não se Aplica')], default='pending', max_length=20, verbose_name='Status Hotel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_travels', to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.clienthub', verbose_name='Hub/Loja')),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travels', to='tickets.ticket', verbose_name='Ordem de Serviço (OS)')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.system', verbose_name='Sistema')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Viagem Técnica',
                'verbose_name_plural': 'Viagens Técnicas',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
