# Generated by Django 6.0.1 on 2026-01-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_techniciantravel'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciantravel',
            name='additional_clients',
            field=models.ManyToManyField(blank=True, related_name='shared_travels', to='tickets.client', verbose_name='Clientes Adicionais'),
        ),
    ]
