# Generated by Django 6.0.1 on 2026-01-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_techniciantravel_additional_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_preferred',
            field=models.BooleanField(default=False, verbose_name='Empresa Preferencial/Padrão'),
        ),
    ]
