# Generated by Django 6.0.1 on 2026-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_client_is_preferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciantravel',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Chegada (Voo)'),
        ),
        migrations.AddField(
            model_name='techniciantravel',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Saída (Voo)'),
        ),
        migrations.AddField(
            model_name='techniciantravel',
            name='flight_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Voo'),
        ),
    ]
