# Generated by Django 6.0.1 on 2026-01-23 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_techniciantravel_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('air', 'Passagem Aérea'), ('bus', 'Passagem de Ônibus'), ('car', 'Carro Alugado')], max_length=20, verbose_name='Tipo de Transporte')),
                ('carrier', models.CharField(help_text='Ex: GOL, Azul, Localiza', max_length=100, verbose_name='Companhia/Locadora')),
                ('transport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número (Voo/Linha/Placa)')),
                ('vehicle_details', models.CharField(blank=True, help_text='Ex: Boeing 737-800, Fiat Mobi', max_length=100, null=True, verbose_name='Aeronave/Veículo')),
                ('origin', models.CharField(help_text='Ex: São Paulo (GRU)', max_length=100, verbose_name='Origem')),
                ('destination', models.CharField(help_text='Ex: Recife (REC)', max_length=100, verbose_name='Destino')),
                ('departure_time', models.DateTimeField(verbose_name='Saída')),
                ('arrival_time', models.DateTimeField(verbose_name='Chegada')),
                ('booking_code', models.CharField(blank=True, help_text='Ex: XYZ123', max_length=50, null=True, verbose_name='Código da Reserva')),
                ('locator', models.CharField(blank=True, max_length=50, null=True, verbose_name='Localizador')),
                ('status', models.CharField(default='Confirmado', max_length=50, verbose_name='Status')),
                ('passenger_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Passageiro')),
                ('passenger_document', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento')),
                ('loyalty_program', models.CharField(blank=True, max_length=100, null=True, verbose_name='Programa de Fidelidade')),
                ('fare_type', models.CharField(blank=True, help_text='Ex: Plus (Inclui bagagem)', max_length=100, null=True, verbose_name='Tarifa')),
                ('seat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Assento')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='travel_tickets/', verbose_name='Anexo (PDF/Imagem)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='tickets.techniciantravel', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Segmento de Viagem',
                'verbose_name_plural': 'Segmentos de Viagem',
                'ordering': ['departure_time'],
            },
        ),
    ]
