# Generated by Django 6.0.1 on 2026-01-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_travelsegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciantravel',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmado'), ('planned', 'Planejado'), ('pending_contract', 'Pendente de Contrato'), ('completed', 'Concluído')], default='planned', max_length=20, verbose_name='Status da Viagem'),
        ),
        migrations.AlterField(
            model_name='travelsegment',
            name='booking_code',
            field=models.CharField(blank=True, help_text='Ex: 9572261127853 (Aéreo) ou Contrato de Locação', max_length=50, null=True, verbose_name='Número do Bilhete / Contrato'),
        ),
        migrations.AlterField(
            model_name='travelsegment',
            name='locator',
            field=models.CharField(blank=True, help_text='Ex: UJMQZS', max_length=50, null=True, verbose_name='Localizador (PNR)'),
        ),
    ]
