# Generated by Django 6.0.1 on 2026-01-27 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_alter_techniciantravel_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='client',
            name='cm_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CM'),
        ),
        migrations.AddField(
            model_name='client',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='client',
            name='periodicity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Periodicidade'),
        ),
        migrations.AddField(
            model_name='client',
            name='service_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário de Atendimento'),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='client',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_clients', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='client',
            name='systems',
            field=models.ManyToManyField(blank=True, related_name='clients', to='tickets.system', verbose_name='Sistemas'),
        ),
        migrations.AddField(
            model_name='client',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='client_allocations', to=settings.AUTH_USER_MODEL, verbose_name='Técnicos Alocados'),
        ),
        migrations.AddField(
            model_name='client',
            name='visits_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de Visitas'),
        ),
    ]
