# Generated by Django 6.0.1 on 2026-01-28 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_client_city_client_cm_code_client_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Checklist')),
                ('department', models.CharField(help_text='Ex: CSO, TI, Manutenção', max_length=100, verbose_name='Departamento/Área')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo de Checklist',
                'verbose_name_plural': 'Modelos de Checklist',
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição da Atividade')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Item do Modelo',
                'verbose_name_plural': 'Itens do Modelo',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DailyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.checklisttemplate', verbose_name='Modelo Utilizado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Checklist Diário',
                'verbose_name_plural': 'Checklists Diários',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição da Atividade')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Realizado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='checklist_photos/', verbose_name='Foto Comprobatória')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('daily_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.dailychecklist')),
            ],
            options={
                'verbose_name': 'Item do Checklist Diário',
                'verbose_name_plural': 'Itens do Checklist Diário',
            },
        ),
    ]
