# Generated by Django 6.0.1 on 2026-01-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_checklisttemplate_checklisttemplateitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychecklistitem',
            name='title',
            field=models.CharField(default='Atividade', max_length=200, verbose_name='Título da Atividade'),
        ),
    ]
