# Generated by Django 6.0.1 on 2026-01-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_dailychecklistitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='title',
            field=models.CharField(default='Atividade', max_length=200, verbose_name='Título da Atividade'),
        ),
    ]
