# Generated by Django 6.0.1 on 2026-01-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_checklisttemplateitem_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChecklistItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='checklist_photos/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tickets.dailychecklistitem')),
            ],
        ),
    ]
