# Generated by Django 6.0.1 on 2026-01-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_dailychecklistitemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychecklist',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PDF Gerado em'),
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
