# Generated by Django 6.0.1 on 2026-01-29 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_dailychecklist_pdf_generated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChecklistItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição do Detalhe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.client', verbose_name='Cliente')),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.clienthub', verbose_name='Hub/Loja')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='tickets.dailychecklistitem')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket', verbose_name='OS Relacionada')),
            ],
            options={
                'verbose_name': 'Detalhe do Item',
                'verbose_name_plural': 'Detalhes dos Itens',
            },
        ),
    ]
