# Generated by Django 6.0.1 on 2026-01-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_dailychecklistitemdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychecklistitemimage',
            name='is_report_image',
            field=models.BooleanField(default=False, verbose_name='Foto do Relatório'),
        ),
    ]
