# Generated by Django 6.0.1 on 2026-01-29 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_dailychecklistitemimage_is_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Se selecionado, esta tarefa será vinculada a este cliente específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.client', verbose_name='Cliente Vinculado'),
        ),
        migrations.AddField(
            model_name='dailychecklistitem',
            name='template_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_items', to='tickets.checklisttemplateitem'),
        ),
    ]
