# Generated by Django 6.0.1 on 2026-01-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_checklisttemplateitem_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_checklist_pdf_debug',
            field=models.BooleanField(default=False, help_text='Se marcado, permite gerar PDF de checklists não finalizados para testes.', verbose_name='Liberar PDF de Checklist (Debug)'),
        ),
    ]
