# Generated by Django 6.0.1 on 2026-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_ticketimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklisttemplateitem',
            options={'ordering': ['parent_id', 'order', 'id'], 'verbose_name': 'Item do Modelo', 'verbose_name_plural': 'Itens do Modelo'},
        ),
        migrations.AlterModelOptions(
            name='dailychecklistitem',
            options={'ordering': ['parent_id', 'order', 'id'], 'verbose_name': 'Item do Checklist Diário', 'verbose_name_plural': 'Itens do Checklist Diário'},
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='field_type',
            field=models.CharField(choices=[('group', 'Grupo'), ('checkbox', 'Checkbox'), ('switch', 'Switch'), ('button', 'Botão'), ('select', 'Select'), ('text', 'Texto')], default='switch', max_length=20, verbose_name='Tipo do Campo'),
        ),
        migrations.AlterField(
            model_name='dailychecklistitem',
            name='field_type',
            field=models.CharField(choices=[('group', 'Grupo'), ('checkbox', 'Checkbox'), ('switch', 'Switch'), ('button', 'Botão'), ('select', 'Select'), ('text', 'Texto')], default='switch', max_length=20, verbose_name='Tipo do Campo'),
        ),
    ]
