# Generated by Django 6.0.1 on 2026-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0047_alter_checklisttemplateitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='alarms_wpp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alarmes WPP'),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_policy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergenciais'),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_used',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergencial Utilizadas'),
        ),
        migrations.AddField(
            model_name='client',
            name='leankeep_assets',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ativos Leankeep'),
        ),
        migrations.AddField(
            model_name='client',
            name='maintenance_plan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Plano de Manutenção'),
        ),
        migrations.AddField(
            model_name='client',
            name='monitoring_cso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Monitoramento CSO'),
        ),
        migrations.AddField(
            model_name='client',
            name='plan_review_due',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Limite para revisão'),
        ),
        migrations.AddField(
            model_name='client',
            name='plan_review_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Revisão do plano'),
        ),
    ]

