# Generated by Django 6.0.1 on 2026-05-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0053_ensure_cadastro_pages_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('origin', models.CharField(choices=[('client', 'Contato do Cliente'), ('jumperfour', 'Planilha JumperFour'), ('manual', 'Cadastro Manual')], default='manual', max_length=20, verbose_name='Origem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='tickets.client', verbose_name='Cliente Associado')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['client', 'name'],
                'unique_together': {('name', 'client', 'origin')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact_requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_as_requester', to='tickets.contactperson', verbose_name='Solicitante (Contato)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_as_responsible', to='tickets.contactperson', verbose_name='Responsável/Executor (Contato)'),
        ),
    ]
