# Generated by Django 6.0.1 on 2026-05-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0054_contactperson_ticket_contact_requester_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactperson',
            unique_together=set(),
        ),
    ]
