# Generated by Django 6.0.1 on 2026-05-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0055_alter_contactperson_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactClient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email")),
                ("phone", models.CharField(blank=True, max_length=20, null=True, verbose_name="Telefone")),
                ("client_ref_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="ID Cliente (referência)")),
                ("client_name", models.CharField(blank=True, default="", max_length=200, verbose_name="Cliente")),
                ("hub_ref_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="ID Hub/Loja (referência)")),
                ("hub_name", models.CharField(blank=True, default="", max_length=200, verbose_name="Hub/Loja")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contato do Cliente",
                "verbose_name_plural": "Contatos dos Clientes",
                "ordering": ["client_name", "hub_name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContactJumper",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email")),
                ("phone", models.CharField(blank=True, max_length=20, null=True, verbose_name="Telefone")),
                ("department", models.CharField(blank=True, default="", max_length=120, verbose_name="Departamento")),
                ("role", models.CharField(blank=True, default="", max_length=120, verbose_name="Cargo/Função")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contato JumperFour",
                "verbose_name_plural": "Contatos JumperFour",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="contact_client_requester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_as_requester",
                to="tickets.contactclient",
                verbose_name="Solicitante (Contato do Cliente)",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="contact_jumper_responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_as_responsible",
                to="tickets.contactjumper",
                verbose_name="Responsável/Executor (Contato JumperFour)",
            ),
        ),
    ]

