# Generated by Django 6.0.1 on 2026-05-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0061_add_ticketstatus_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
