# Generated by Django 6.0.5 on 2026-05-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0063_activesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
