# Generated by Django 6.0.5 on 2026-06-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0064_alter_activesession_id'),
        ('tickets', '0064_ticket_created_by'),
    ]

    operations = [
    ]
