# Generated by Django 6.0.1 on 2026-06-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0072_shifthandoverentry_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifthandoverentry',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_entries', to='tickets.ticket', verbose_name='Ticket gerado'),
        ),
    ]
