# Generated by Django 6.0.1 on 2026-06-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0073_shifthandoverentry_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthub',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
