# Generated by Django 6.0.1 on 2026-06-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0074_clienthub_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstatus',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem personalizada (se não definir, usa a badge com a cor escolhida)', null=True, upload_to='ticket_status_icons/', verbose_name='Imagem do Status'),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='image_height',
            field=models.PositiveIntegerField(default=26, verbose_name='Altura da Imagem (px)'),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='image_width',
            field=models.PositiveIntegerField(default=100, verbose_name='Largura da Imagem (px)'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='color',
            field=models.CharField(default='secondary', help_text='Ex: primary, secondary, success, danger, warning, info, dark', max_length=20, verbose_name='Cor (Bootstrap)'),
        ),
    ]
