# Generated by Django 6.0.1 on 2026-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0075_ticketstatus_image_ticketstatus_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='open', max_length=50, verbose_name='Status'),
        ),
    ]
