# Generated by Django 6.0.1 on 2026-06-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0076_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstatus',
            name='row_color',
            field=models.CharField(blank=True, default='', help_text='Cor Bootstrap para o fundo do card na lista: primary, success, warning, danger, info, secondary, dark. Deixe em branco para usar o padrão.', max_length=20, verbose_name='Cor de Fundo (Bootstrap)'),
        ),
    ]
