# Generated by Django 6.0.1 on 2026-06-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0077_ticketstatus_row_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketstatus',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Código HEX da cor da badge (ex: #28a745).', max_length=20, verbose_name='Cor (Hex)'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='row_color',
            field=models.CharField(blank=True, default='', help_text='Código HEX da cor de fundo do card na lista (ex: #28a745). Deixe em branco para usar o padrão.', max_length=20, verbose_name='Cor de Fundo (Hex)'),
        ),
    ]
