# Generated by Django 6.0.1 on 2026-06-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0078_alter_ticketstatus_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstatus',
            name='font_color',
            field=models.CharField(blank=True, default='', help_text='Código HEX da cor do texto da badge (ex: #ffffff). Deixe em branco para contraste automático.', max_length=20, verbose_name='Cor da Fonte (Hex)'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Código HEX da cor de fundo da badge (ex: #28a745).', max_length=20, verbose_name='Cor de Fundo (Hex)'),
        ),
    ]
