# Generated by Django 6.0.1 on 2026-07-06 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0079_ticketstatus_font_color_alter_ticketstatus_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ai_api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='Chave de API'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_enabled',
            field=models.BooleanField(default=False, verbose_name='Ativar Assistente de IA'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_model',
            field=models.CharField(blank=True, help_text='Deixe em branco para usar o modelo padrão do provedor', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google Gemini')], default='deepseek', max_length=20, verbose_name='Provedor de IA'),
        ),
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Chat IA',
                'verbose_name_plural': 'Sessões de Chat IA',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('tool', 'Ferramenta')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.aichatsession')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat IA',
                'verbose_name_plural': 'Mensagens de Chat IA',
                'ordering': ['created_at'],
            },
        ),
    ]
