# Generated by Django 6.0.1 on 2026-07-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0083_ai_user_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_last_proactive_alert',
            field=models.DateField(blank=True, null=True, verbose_name='Último alerta proativo do Jota4 (mensagens/turno pendentes)'),
        ),
    ]
