# Generated by Django 6.0.1 on 2026-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0084_userprofile_ai_proactive_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ai_last_proactive_alert',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_proactive_alert_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas de aviso do Jota4 sobre pendências não resolvidas'),
        ),
    ]
