# Generated by Django 6.0.1 on 2026-07-10 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0085_userprofile_ai_alert_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_threads_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_threads_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversa Particular',
                'verbose_name_plural': 'Conversas Particulares',
                'ordering': ['-updated_at'],
                'unique_together': {('user_a', 'user_b')},
            },
        ),
        migrations.CreateModel(
            name='PrivateChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_ai_message', models.BooleanField(default=False, verbose_name='Mensagem do Jota4')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_private_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remetente (vazio = Jota4)')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.privatechatthread')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat Particular',
                'verbose_name_plural': 'Mensagens de Chat Particular',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message_id', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_read_states', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='tickets.privatechatthread')),
            ],
            options={
                'verbose_name': 'Estado de Leitura (Chat Particular)',
                'verbose_name_plural': 'Estados de Leitura (Chat Particular)',
                'unique_together': {('thread', 'user')},
            },
        ),
    ]
