# Generated by Django 6.0.1 on 2026-07-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0086_private_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatreadstate',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Limpou o histórico até (somente para este usuário)'),
        ),
    ]
