# Generated by Django 6.0.1 on 2026-07-10 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0087_private_chat_clear_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITicketBatchDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.PositiveIntegerField(verbose_name='Quantidade total de OS no lote')),
                ('shared_defaults', models.JSONField(blank=True, default=dict, verbose_name='Campos padrão compartilhados')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='Rascunhos de cada OS (um por posição)')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_ticket_batch_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de OS (Chat IA)',
                'verbose_name_plural': 'Lotes de OS (Chat IA)',
            },
        ),
    ]
