# Generated by Django 6.0.1 on 2026-07-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0088_ai_ticket_batch_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='ai_chat_audio/%Y/%m/', verbose_name='Áudio (mensagem de voz)'),
        ),
    ]
