# Generated by Django 6.0.1 on 2026-07-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0089_ai_chat_message_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voice_wakeword_enabled',
            field=models.BooleanField(default=False, verbose_name='Escuta por voz (chamar o Jota4 dizendo o nome dele)'),
        ),
    ]
