# Generated by Django 6.0.1 on 2026-07-12 14:21

from django.db import migrations, models


def migrate_existing_ai_config(apps, schema_editor):
    """Se já havia um provedor/chave configurado no SystemSettings singleton,
    migra pra uma linha em AIProviderConfig (ativa), pra não perder a config
    que já estava funcionando."""
    SystemSettings = apps.get_model('tickets', 'SystemSettings')
    AIProviderConfig = apps.get_model('tickets', 'AIProviderConfig')

    settings_obj = SystemSettings.objects.first()
    if not settings_obj:
        return

    old_api_key = getattr(settings_obj, 'ai_api_key', '') or ''
    if not old_api_key:
        return

    AIProviderConfig.objects.create(
        name='Configuração migrada',
        provider=getattr(settings_obj, 'ai_provider', '') or 'deepseek',
        model=getattr(settings_obj, 'ai_model', '') or '',
        api_key=old_api_key,
        is_active=True,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0090_userprofile_voice_wakeword_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google Gemini')], default='deepseek', max_length=20, verbose_name='Provedor de IA')),
                ('model', models.CharField(blank=True, help_text='Deixe em branco para usar o modelo padrão do provedor', max_length=100, verbose_name='Modelo')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='Chave de API')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativa (em uso pelo Jota4)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de IA',
                'verbose_name_plural': 'Configurações de IA',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.RunPython(migrate_existing_ai_config, noop_reverse),
        migrations.RemoveField(
            model_name='systemsettings',
            name='ai_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='ai_provider',
        ),
    ]
