# Generated by Django 6.0.1 on 2026-07-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0091_aiproviderconfig_remove_systemsettings_ai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='google_search_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chave de API (Google Custom Search)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='google_search_engine_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID do Mecanismo de Busca (cx)'),
        ),
    ]
