# Generated by Django 6.0.1 on 2026-07-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0092_systemsettings_google_search_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='search_provider',
            field=models.CharField(choices=[('google', 'Google Custom Search'), ('tavily', 'Tavily')], default='google', max_length=20, verbose_name='Provedor de Busca'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tavily_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chave de API (Tavily)'),
        ),
    ]
