# Generated by Django 6.0.1 on 2026-07-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0093_systemsettings_search_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='google_tts_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chave de API (Google Cloud Text-to-Speech)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tts_provider',
            field=models.CharField(choices=[('browser', 'Navegador (gratuito)'), ('google', 'Google Cloud Text-to-Speech')], default='browser', max_length=20, verbose_name='Provedor de Voz (TTS)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tts_enabled',
            field=models.BooleanField(default=False, verbose_name='Respostas do Jota4 em voz alta'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tts_voice_gender',
            field=models.CharField(choices=[('female', 'Feminina'), ('male', 'Masculina')], default='female', max_length=10, verbose_name='Voz preferida'),
        ),
    ]
