# Generated by Django 6.0.1 on 2026-07-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0094_systemsettings_google_tts_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='elevenlabs_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chave de API (ElevenLabs)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='elevenlabs_voice_id_female',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID da Voz Feminina (ElevenLabs)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='elevenlabs_voice_id_male',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID da Voz Masculina (ElevenLabs)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='tts_provider',
            field=models.CharField(choices=[('browser', 'Navegador (gratuito)'), ('google', 'Google Cloud Text-to-Speech'), ('elevenlabs', 'ElevenLabs')], default='browser', max_length=20, verbose_name='Provedor de Voz (TTS)'),
        ),
    ]
