# Generated by Django 6.0.1 on 2026-07-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0095_systemsettings_elevenlabs_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='elevenlabs_voice_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Voz ElevenLabs'),
        ),
    ]
