# Generated by Django 6.0.1 on 2026-07-16 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0096_userprofile_elevenlabs_voice_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketListOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField(default=list, verbose_name='IDs das OS na ordem escolhida')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_list_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordem da Lista de OS',
                'verbose_name_plural': 'Ordens da Lista de OS',
            },
        ),
    ]
