# Generated by Django 6.0.1 on 2026-07-16 16:05

from django.db import migrations, models


def _copy_flat_settings_into_provider_configs(apps, schema_editor):
    """
    Antes de remover os campos soltos de busca/voz do SystemSettings, copia o
    que já estava configurado pra uma primeira linha (já ativa) em cada tabela
    nova — quem já tinha uma integração funcionando não perde a config.
    """
    SystemSettings = apps.get_model('tickets', 'SystemSettings')
    SearchProviderConfig = apps.get_model('tickets', 'SearchProviderConfig')
    VoiceProviderConfig = apps.get_model('tickets', 'VoiceProviderConfig')

    settings_obj = SystemSettings.objects.first()
    if not settings_obj:
        return

    if settings_obj.google_search_api_key or settings_obj.tavily_api_key or settings_obj.google_search_engine_id:
        SearchProviderConfig.objects.create(
            name='Configuração migrada',
            provider=settings_obj.search_provider or 'google',
            api_key=(settings_obj.google_search_api_key if settings_obj.search_provider != 'tavily' else settings_obj.tavily_api_key) or '',
            google_search_engine_id=settings_obj.google_search_engine_id or '',
            is_active=True,
        )

    if settings_obj.google_tts_api_key or settings_obj.elevenlabs_api_key:
        provider = settings_obj.tts_provider or 'browser'
        VoiceProviderConfig.objects.create(
            name='Configuração migrada',
            provider=provider,
            api_key=(settings_obj.elevenlabs_api_key if provider == 'elevenlabs' else settings_obj.google_tts_api_key) or '',
            elevenlabs_voice_id_female=settings_obj.elevenlabs_voice_id_female or '',
            elevenlabs_voice_id_male=settings_obj.elevenlabs_voice_id_male or '',
            is_active=True,
        )


def _seed_integrations_page_permission(apps, schema_editor):
    """
    Registra a tela de Integrações no sistema de permissões por página já
    existente, e bloqueia explicitamente o nível 'admin' — deixando, por
    padrão, só o Super Admin acessar (que sempre passa direto pelo
    middleware, independente de qualquer RolePagePermission). Um Super Admin
    pode depois liberar outros níveis normalmente pela tela de Permissões,
    já que ela lista qualquer AppPage cadastrada.
    """
    AppPage = apps.get_model('tickets', 'AppPage')
    RoleLevel = apps.get_model('tickets', 'RoleLevel')
    RolePagePermission = apps.get_model('tickets', 'RolePagePermission')

    page, _ = AppPage.objects.get_or_create(
        url_name='settings_integrations',
        defaults={
            'code': 'settings_integrations',
            'name': 'Integrações',
            'group': 'Configurações',
            'order': 0,
            'is_enabled': True,
        },
    )

    admin_role = RoleLevel.objects.filter(code='admin').first()
    if admin_role:
        RolePagePermission.objects.get_or_create(
            role=admin_role, page=page, defaults={'allowed': False},
        )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0097_ticketlistorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('provider', models.CharField(choices=[('google', 'Google Custom Search'), ('tavily', 'Tavily')], default='google', max_length=20, verbose_name='Provedor de Busca')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='Chave de API')),
                ('google_search_engine_id', models.CharField(blank=True, max_length=100, verbose_name='ID do Mecanismo de Busca (cx) — só Google')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativa (em uso pelo Jota4)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Busca',
                'verbose_name_plural': 'Configurações de Busca',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VoiceProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('provider', models.CharField(choices=[('browser', 'Navegador (gratuito)'), ('google', 'Google Cloud Text-to-Speech'), ('elevenlabs', 'ElevenLabs')], default='browser', max_length=20, verbose_name='Provedor de Voz (TTS)')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='Chave de API')),
                ('elevenlabs_voice_id_female', models.CharField(blank=True, max_length=100, verbose_name='ID da Voz Feminina (ElevenLabs)')),
                ('elevenlabs_voice_id_male', models.CharField(blank=True, max_length=100, verbose_name='ID da Voz Masculina (ElevenLabs)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativa (em uso pelo Jota4)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Voz',
                'verbose_name_plural': 'Configurações de Voz',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.RunPython(_copy_flat_settings_into_provider_configs, _noop_reverse),
        migrations.RunPython(_seed_integrations_page_permission, _noop_reverse),
        migrations.RemoveField(
            model_name='systemsettings',
            name='elevenlabs_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='elevenlabs_voice_id_female',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='elevenlabs_voice_id_male',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='google_search_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='google_search_engine_id',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='google_tts_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='search_provider',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='tavily_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='tts_provider',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='universal_elevenlabs_voice_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID da Voz ElevenLabs Universal'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='universal_tts_voice_gender',
            field=models.CharField(choices=[('female', 'Feminina'), ('male', 'Masculina')], default='female', max_length=10, verbose_name='Gênero da Voz Universal'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='voice_selection_mode',
            field=models.CharField(choices=[('per_user', 'Cada usuário escolhe a própria voz'), ('universal', 'Voz única para todos (definida pelo Super Admin)')], default='per_user', max_length=20, verbose_name='Modo de Seleção de Voz'),
        ),
    ]
