# Generated by Django 6.0.1 on 2026-07-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0098_integration_provider_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_receipt_notified',
            field=models.BooleanField(default=False, verbose_name='Confirmação de leitura já enviada'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_receipt_requested',
            field=models.BooleanField(default=False, verbose_name='Solicitar confirmação de leitura'),
        ),
        migrations.AddField(
            model_name='notification',
            name='urgency',
            field=models.CharField(choices=[('high', 'Alto'), ('medium', 'Médio'), ('low', 'Baixo')], default='medium', max_length=10, verbose_name='Urgência'),
        ),
    ]
