# Generated by Django 6.0.1 on 2026-07-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0099_notification_deleted_by_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='voice_globally_enabled',
            field=models.BooleanField(default=True, verbose_name='Ativar Voz e Áudio (geral)'),
        ),
    ]
